const dataList = {
    "list1":{
        "name":'同事',
        "list":[
            {
                "name":'孙悟空',
                "sex":'男',
                "like":'打篮球'
            },
            {
                "name":'达摩',
                "sex":'女',
                "like":'打乒乓球'
            },
            {
                "name":'李信',
                "sex":'男',
                "like":'开双刀'
            },
            {
                "name":'花木兰',
                "sex":'男',
                "like":'切重剑'
            }
        ]
    },
    "list2":{
        "name":'亲戚',
        "list":[
            {
                "name":'鲁班',
                "sex":'男',
                "like":'一直平A'
            },
            {
                "name":'虞姬',
                "sex":'女',
                "like":'翘屁股'
            },
            {
                "name":'后羿',
                "sex":'男',
                "like":'大鸟'
            },
            {
                "name":'狄仁杰',
                "sex":'男',
                "like":'扔飞镖'
            }
        ]
    },
    "list3":{
        "name":'朋友',
        "list":[
            {
                "name":'诸葛亮',
                "sex":'男',
                "like":'贴身打'
            },
            {
                "name":'貂蝉',
                "sex":'女',
                "like":'飞来飞去'
            },
            {
                "name":'张良',
                "sex":'男',
                "like":'放法阵'
            },
            {
                "name":'妲己',
                "sex":'女',
                "like":'专治花里胡哨'
            }
        ]
    }
}
export default dataList;